### ISSUE TITLE
If remotely doesn't return a promise, error is ambiguous

### ISSUE THREAD

**Issue by engineersamuel** [jhollingworth/marty#94]
It would be great if Marty could return a descriptive error message when remotely does not return a promise.   While this is bug not against Marty, the error makes it very difficult to track down.  For example. 

```
    getComments: function (id) {
        return this.fetch({
            id: id,
            locally: function () {
                return this.state[id];
            },
            remotely: function () {
                return CommentAPI.getComments(id);
            }
        });
    },

```

And 

```
var API = Marty.createStateSource({
    type: 'http',
    getComments: function (id) {
        Q($.get(`/comments/${id}`)).then((comments) => {
            return CommentSourceActions.receiveComments(caseNumber, comments)
        });
    }
});

module.exports = API;
```

Returns the following error which is very hard to track down:

```
 TypeError: Cannot read property 'defaultProps' of undefined
    at Object.ReactElement.createElement (https://foo.redhat.com/assets/main.js:32465:12)
    at Object.ReactElementValidator.createElement (https://foo.redhat.com/assets/main.js:32760:47)
    at Object.ReactLegacyElementFactory.wrapCreateElement.legacyCreateElement [as createElement] (https://foo.redhat.com/assets/main.js:34109:29)
    at Object.React.createClass.renderComments.state.comments.when.failed (https://foo.redhat.com/assets/main.js:82465:31)
```

Note that it was only when I realized the remotely was returning undefined did I realize I must not have returned the promise within the API portion, that fixed it.

There are other places where a small mistake takes quite a bit of time to trace where the error was due to the ambiguous error messages.

Loving this flux abstraction btw!

**Comment by jhollingworth** [comment]
Great idea, fixed. Thanks!
